---
- name: "Ensure openssl is installed"
  apt: name=openssl state=latest

- name: "Delete ca-certs directory"
  file:
    path: "{{ item }}"
    state: absent
    owner: root
    group: root
  with_items:
    - "{{ ca_certs_dir }}"

- name: "Make configuration directory"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
  - "{{ ca_certs_dir }}"

- name: "Deploy configuration items"
  template:
    src: "{{ item }}.j2"
    dest: "{{ ca_certs_dir }}/{{ item }}"
    owner: root
    group: root
  with_items:
    - serial
    - ca.conf

- name: "set CA_SUBJECT var"
  set_fact:
    ca_subject: '/C={{ ca_country }}/ST={{ ca_state }}/L={{ ca_locality }}/O={{ ca_organization }}/OU={{ ca_organizationalunit }}/CN={{ ca_commonname }}/emailAddress={{ ca_email }}'
  when: ca_subject is not defined

- debug: var=ca_subject

- name: "Generate private key && Create root CA files"
  shell:
    "{{ item }}"
  args:
    chdir: "{{ ca_certs_dir }}"
  with_items:
    - "openssl genrsa -out {{ ca_key }} 2048"
    - "openssl req -config /usr/lib/ssl/openssl.cnf -new -key {{ ca_key }} -x509 -days 1825 -out {{ ca_cert }} -passin pass:{{ ca_rootca_password }} -subj \"{{ ca_subject }}\""
