---
- name: "generate CA private key"
  shell:
    "{{ item }}"
  args:
    chdir: "{{ ca_certs_dir }}"
  with_items:
    - "openssl genrsa -out {{ ca_key }} 2048"
  when: _ca_key_exists is undefined or ca_force_create == true

- name: "greate root CA cert"
  shell:
    "{{ item }}"
  args:
    chdir: "{{ ca_certs_dir }}"
  with_items:
    - "openssl req -config {{ ca_certs_dir }}/ca.conf -new -key {{ ca_key }} -x509 -days 1825 -out {{ ca_cert }} -passin pass:{{ ca_rootca_password }} -subj \"{{ ca_subject }}\""
  when: _ca_missing_cert is undefined or ca_force_create == true